#!/bin/bash

pushd server
npm run build
popd

pushd client
npm run build
popd

cp client/build/bundle.js .build/client/build
cp client/index.html .build/client
cp server/build/server.js .build

tar -czf release.tar.gz .build

ssh pi@pinette.local 'rm -rf /home/pi/apps/pi-face-dev/*'
scp release.tar.gz pi@pinette.local:/home/pi/apps/pi-face-dev/
ssh pi@pinette.local 'cd /home/pi/apps/pi-face-dev && tar -xf release.tar.gz'
ssh pi@pinette.local 'cp -r /home/pi/apps/pi-face-dev/.build/* /home/pi/apps/pi-face-dev'
ssh pi@pinette.local 'rm -rf /home/pi/apps/pi-face-dev/.build /home/pi/apps/pi-face-dev/release.tar.gz'
