export const RECEIVED_FILES = "PODCAST_RECEIVED_FILES";
export const PLAYING_FILE = "PODCAST_PLAYING_FILE";
export const RESUME = "PODCAST_RESUME";
export const PAUSE = "PODCAST_PAUSE";
export const STOP = "PODCAST_STOP";